---
- hosts: ansible-server
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/kubernetes

  - name: create tag to image
    command: docker tag simple-devops-image utube/docker_ci

  - name: push image on to dockerhub
    command: docker push utube/docker_ci

  - name: remove docker images form ansible server
    command: docker rmi tomcat simple-devops-image:latest utube/docker_ci
    ignore_errors: yes
